# Generated by Django 6.0.7 on 2026-07-19 14:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(help_text='Must be between 18 and 65', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3, verbose_name='Blood Group')),
                ('division', models.CharField(choices=[('Barishal', 'Barishal'), ('Chattogram', 'Chattogram'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], db_index=True, max_length=50, verbose_name='Division')),
                ('district', models.CharField(db_index=True, max_length=100, verbose_name='District')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='Last Donation Date')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Available for Donation')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Donor')),
                ('medical_notes', models.TextField(blank=True, help_text='Conditions/medications relevant to donation eligibility', verbose_name='Medical Notes')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('45'))], verbose_name='Weight (kg)')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('total_donations', models.PositiveIntegerField(default=0, verbose_name='Total Donations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['blood_group', 'division', 'is_available'], name='donors_dono_blood_g_36e584_idx')],
            },
        ),
    ]
